FROM dockcross/manylinux-x64

ENV DEFAULT_DOCKCROSS_IMAGE dockcross/xmanylinux-x64

ARG LIB_DIR=lib64

#include "common.xmanylinux"

# Reset PATH
ENV PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
ENV LD_LIBRARY_PATH="/usr/local/lib64:/usr/local/lib"

# Configure default environment
ENV PATH="/opt/python/cp27-cp27mu/bin/:${PATH}"
ENV LD_LIBRARY_PATH="/opt/python/cp27-cp27mu/lib/:${LD_LIBRARY_PATH}"
ENV PATH="/opt/llvm60/bin:${PATH}"
ENV JAVA_HOME="/opt/jdk1.8.0_191"
ENV JRE_HOME="/opt/jdk1.8.0_191/jre"
ENV PATH="/opt/jdk1.8.0_191/bin:/opt/jdk1.8.0_191/jre/bin:${PATH}"
ENV PATH="/opt/apache-maven-3.3.9/bin:${PATH}"
ENV LD_LIBRARY_PATH="/opt/llvm60/lib:${LD_LIBRARY_PATH}"

ENV CROSS_TRIPLE x86_64-linux-gnu
ENV CROSS_ROOT /opt/llvm60/bin
ENV AS=${CROSS_ROOT}/llvm-as \
    AR=${CROSS_ROOT}/llvm-ar \
    CC=${CROSS_ROOT}/clang \
    CPP=${CROSS_ROOT}/clang-cpp \
    CXX=${CROSS_ROOT}/clang++ \
    LD=${CROSS_ROOT}/ld.lld \
    LDFLAGS=-fuse-ld=lld
COPY xmanylinux-x64/Toolchain.cmake ${CROSS_ROOT}/../lib/
ENV CMAKE_TOOLCHAIN_FILE="/opt/llvm60/lib/Toolchain.cmake"

# Flags
ENV CFLAGS="-march=x86-64 -mtune=generic"
ENV CXXFLAGS="-march=x86-64 -mtune=generic"
ENV FFLAGS="-march=x86-64 -mtune=generic"

# Allow to run 32 bits binary
RUN yum -y install glibc.i686 libgcc_s.so.1

